#!/bin/bash

# -----------------------------------------

# settings 
ssc=/mnt/nas2_ip10-4-56-190/mcdata

tempdir=/tmp/playg
mkdir -p ${tempdir}
timestart=$(date +"%Y.%m.%d_%H.%M.%S")
tfc=${tempdir}/$0_list_${timestart}
# end settings.
# -----------------------------------------

echo "-+-+--+-+-  Starting  $(basename -- "$0")  $(date +"_%Y.%m.%d_%H.%M.%S")" >> ${tempdir}/$(basename -- "$0")$(date +"_%Y.%m.%d").log

# -----------------------------------------

#  start here

cd "${ssc}"
#find . -type f  |grep -P "_20\d{4}T\d{6}" | sort -n > ${tfc}
find . -type f  -mtime +365 > ${tfc}.a
echo "  start-b $(basename -- "$0")  $(date +"_%Y.%m.%d_%H.%M.%S")" >> ${tempdir}/$(basename -- "$0")$(date +"_%Y.%m.%d").log
cat ${tfc}.a  | sort -n  > ${tfc}.b
#cat ${tfc}.b  > ${tfc}.c

echo file list..
cat ${tfc}.b
echo "  end $(basename -- "$0")  $(date +"_%Y.%m.%d_%H.%M.%S")" >> ${tempdir}/$(basename -- "$0")$(date +"_%Y.%m.%d").log
