#!/bin/bash

# -----------------------------------------

# settings 
ssc=/mnt/nas2_ip10-4-56-190/mcdata

tempdir=/tmp/moveimg
mkdir -p ${tempdir}
timestart=$(date +"%Y.%m.%d_%H.%M.%S")
rslognamepart=_findnas2
tfc=${tempdir}/findfilesnas2_${timestart}.txt

# end settings.
# -----------------------------------------

echo "-+-+--+-+-  Starting  $(basename -- "$0")  $(date +"_%Y.%m.%d_%H.%M.%S")" >> ${tempdir}/$(basename -- "$0")$(date +"_%Y.%m.%d").log

# -----------------------------------------

#  start here

cd "${ssc}"
#find . -type f  |grep -P "_20\d{4}T\d{6}" | sort -n > ${tfc}
find . -type f   > ${tfc}
echo file list..
cat ${tfc}
echo "  end $(basename -- "$0")  $(date +"_%Y.%m.%d_%H.%M.%S")" >> ${tempdir}/$(basename -- "$0")$(date +"_%Y.%m.%d").log
